mobile_game_analytics:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: elated-badge-466312-p3
      dataset: mobile_analytics_dev
      threads: 4
      timeout_seconds: 300
      location: US
      keyfile: ./dbt-key.json
    prod:
      type: bigquery
      method: service-account
      project: elated-badge-466312-p3
      dataset: mobile_analytics_prod
      threads: 4
      timeout_seconds: 300
      location: US
      keyfile: ./dbt-key.json
  target: dev